### ISSUE TITLE
Fail to start on clean installed High Sierra

### ISSUE THREAD

**Issue by znz** [rabbit-shocker/rabbit#111]
- Install High Sierra
- Install [Homebrew](https://brew.sh/)
- Install [anyenv](https://github.com/riywo/anyenv), rbenv, ruby 2.4.3
- `gem install rabbit`
- `rabbit` causes `(null)-WARNING **: Failed to load shared library '@rpath/libpoppler-glib.8.dylib' referenced by the typelib: dlopen(@rpath/libpoppler-glib.8.dylib, 9): image not found` ([Full trace](https://gist.github.com/znz/3904e4693e13587b3814ae4e40603e04))

I tried on VirtualBox (ref http://tobiwashere.de/2017/10/virtualbox-how-to-create-a-macos-high-sierra-vm-to-run-on-a-mac-host-system/ via [Virtualboxで動くHigh SierraのVMをつくる](https://qiita.com/nofrmm/items/6091906469ebb4ec28bb)), but same error occurred.

**Comment by kou** [comment]
It's related to ruby-gnome2/ruby-gnome2#1124.

I think that

* Poppler GLib uses CMake instead of GNU Autotools since 0.62.0.
* CMake uses `@rpath` instead of absolute path by default. See also: https://cmake.org/Wiki/CMake_RPATH_handling#Mac_OS_X_and_the_RPATH
* Homebrew shouldn't use `@rpath` to prevent loading unexpected libraries.
* Formula for Poppler should add `-DCMAKE_MACOSX_RPATH=OFF` CMake option to use absolute path instead of `@rpath`. See also: https://cmake.org/cmake/help/latest/variable/CMAKE_MACOSX_RPATH.html#variable:CMAKE_MACOSX_RPATH
  * Or GObject Introspection is improved to generate `.gir` file with `@rpath` substitution even when `otool -L` returns path that includes `@rpath`.

**Comment by kou** [comment]
This has been solved.
